### ISSUE TITLE
ÿþ / 0xfffe (bom) as first character when trying to read files downloaded from Bandcamp

### ISSUE THREAD

**Issue by christian-schneider** [chicio/ID3TagEditor#1]
I am testing with mp3 files downloaded from Bandcamp and all the tags have the wretched utf16 unicode bom, and I am now since hours trying to get rid of it. I am attaching a file that I am testing with the demo app that resulting in the output displayed on the attached image. 
<img width="434" alt="bom-tags" src="https://user-images.githubusercontent.com/28393783/39304512-363d4744-495a-11e8-94ed-8eeff5b618a7.png">

[Laraaji.mp3.zip](https://github.com/chicio/ID3TagEditor/files/1951005/Laraaji.mp3.zip)

**Comment by christian-schneider** [comment]
While searching up and down the net and forums, some other mp3 players / readers seem to have experienced this in the past as well. It would be great to have it fixed right here in the library, not just in my "client".

**Comment by chicio** [comment]
Hi @christian-schneider,
thanks for your feedback. I will start to investigate in issue right now. I will let you know when a fix is available.
Best regards,
Fabrizio.

**Comment by chicio** [comment]
Hi @christian-schneider,
I fixed the encoding bug and opened a pull request with the modification.
If you want you can checkout the branch of this pull request

[https://github.com/chicio/ID3TagEditor/pull/2](https://github.com/chicio/ID3TagEditor/pull/2)

and test it locally. I'm waiting to merge it because I have to do some tests with some mp3 on the mp3 reader of my car (this is the reason behind the born of this library 😆).
Let me know if it works for you.

Thanks,
Fabrizio.

**Comment by christian-schneider** [comment]
Wow, thanks very much Fabrizio! If your tests pass, please merge it into master then. I will test a lot of mp3's with the library and if anything else comes up, i ll report back immediately ;). Have a good weekend.

**Comment by chicio** [comment]
Hi @christian-schneider,
version 1.1.1 release (also on cocoapods if you need it).
Thanks,
Fabrizio.

**Comment by christian-schneider** [comment]
@chicio Fantastic, again, thanks very much! I am using ID3TagEditor with Carthage atm, some of the projects I wanted quit supporting Pods lately (Swifty Dropbox), then I found Carthage to be very much to my taste. Still using Pods just for Swiftlint and Swiftgen. I am currently working on a swift adaption (atm still closed/stealth) of my unfinished Liber music player, of which the Obj-C basic is on my github.  I will use ID3TagEditor for reading and writing tags, this should be a good benchmark for the lib (y)
