### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by jeanparker** [chicio/ID3TagEditor#10]
**Describe the bug**
Fails to build on Ubuntu 16.04 with Swift 4.2

**To Reproduce**
1. Clone repo
2. swift build
3. ID3TagEditor: error: package has unsupported layout; found loose source files: /home/userx/Swift/ID3TagEditor/Source/ID3TagEditor.swift, /home/userx/Swift/ID3TagEditor/Source/ID3TagEditorError.swift, /home/userx/Swift/ID3TagEditor/Source/ID3Version.swift

**Expected behavior**
Successful build

**Screenshots**

**Device (please complete the following information):**
 - Model: [e.g. iPhone6]

**Additional context**

**Comment by chicio** [comment]
Hi @jeanparker ,
thank you for your reporting.
I will investigate the problem in the next days and I will warn you when I have a fix for the problem.
Fabrizio.

**Comment by chicio** [comment]
Hi @jeanparker,
I pushed today a new version of ID3TagEditor fully compatible with the Swift Package Manager.
You can find a demo here:

[ID3TagEditor\Demo Ubuntu](https://github.com/chicio/ID3TagEditor/tree/master/Demo/Demo%20Ubuntu)

I tested it on Ubuntu 18.04.1.
To try the demo you just need to run (if you want)`swift build` and then `swift run`.
This version, 2.2.0, is not yet released on Cocoapods (but I don't think you need it).

Thank you and continue to support my work by starring my repositories 😃.
Let me know if you have any other problem.

Best regards,
Fabrizio.

**Comment by jeanparker** [comment]
Grazie mille Fabrizio :smiley:
