### ISSUE TITLE
At least some attached PNGs cause the file to become corrupted

### ISSUE THREAD

**Issue by flagoworld** [chicio/ID3TagEditor#15]
**Describe the bug**
When writing this PNG into a wav file, the file gets corrupted:

https://ia800901.us.archive.org/32/items/mbid-c2dab6ed-1a4e-49a6-9abc-6be95c03dbda/mbid-c2dab6ed-1a4e-49a6-9abc-6be95c03dbda-4804372334.png

Trying to run the resulting file through ffprobe or ffmpeg throws errors.

**Device (please complete the following information):**
 - OS: MacOS

**Comment by chicio** [comment]
Hi @flagoworld ,

wave file are not supported by the library.

ps.: support my work by starring my repos 😊

Best regards,
Fabrizio.
