### ISSUE TITLE
Add Unsynchronised lyrics frame

### ISSUE THREAD

**Issue by andriypohorilko** [chicio/ID3TagEditor#22]
Hi, is it possible to add editing Lyrics tag?

**Comment by NCrusher74** [comment]
FYI I'm working on a fork that incorporates about 25 more tags, including lyrics, I just need to get a few wrinkles worked out and make sure it works.

**Comment by NCrusher74** [comment]
The version of this tag that was added a few days ago isn't compliant and looks strange in certain metadata viewers (for instance, it comes out as a string of characters from one of the Asian alphabets in MediaInfo.) I am working on trying to make this compliant still.

@chicio I have a pull request open on my own fork of this repo for the purposes of working on it, and I could use some guidance with regard to the parsers and adapters needed, if you can find the time. Thank you!

**Comment by chicio** [comment]
It appears strange because as we already discussed it doesn' t implement the  id3 standard in the right way. Open a MR on this repo and I will check the progress. We can also decide to remove for the moment this tag with a previous MR. If you want you can open both (the one to remove it temporary and the one with the correct implementation).

**Comment by NCrusher74** [comment]
I feel like I'm 80% of the way to having it implemented, so there's no sense removing it right now. I'd rather just figure out how to write the parsers and adapters and implement it correctly.

I'll open the PR here.

**Comment by chicio** [comment]
Hi @andriypohorilko and @NCrusher74 ,

I finally had time to implement this feature, fully compliant to the ID3 standard. Soon I will merge on master this PR

#40 Unsynchronised lyrics

I will NOT release immediately a new version. I will develop other some new stuff before going live (new frames and some other cool stuff). So if you need to use immediately this new feature use the master version after the merge.

Thank you all for your patience.
Fabrizio
