### ISSUE TITLE
Read another frames

### ISSUE THREAD

**Issue by jvegaf** [chicio/ID3TagEditor#30]
I will like can read the another frames, like the PRIV frames. How we can do it? 

Thanks !

Best Regards

**Comment by chicio** [comment]
Hi @jvegaf ,
if the frames you're trying to read is not in the list of supported frames in the readme, than you have to add the implementation for this specific frame (following the id3.org specifications). Feel free to open a PR.
Best regards,
Fabrizio.

PS (remember to star the ID3TagEditor ⭐️ )
