### ISSUE TITLE
DiscPosition Tag disappears when attach cover art

### ISSUE THREAD

**Issue by xanadu6291** [chicio/ID3TagEditor#35]
**Describe the bug**
DiscPosition Tag works expected without attaching cover art, however, it was lost with attaching cover art.

**To Reproduce**
1. Prepare any mp3 file.
2. Prepare any jpg image.
3. Run the following code.

		import Cocoa
		import ID3TagEditor
		
		class ViewController: NSViewController {
		
			@IBAction func Button(_ sender: Any) {
			

                         let coverArtPath = "/Users/roushi/Music/test.jpg"
		        let coverArtImage = NSImage(contentsOfFile: coverArtPath)
		        let coverArtData = coverArtImage?.tiffRepresentation
		                
		        let mp3FilePath = "/Users/roushi/Music/test.mp3"
		        
		        do {
		                let id3Tag = ID3Tag(
		                    version: .version3,
		                    frames: [
		                        .DiscPosition : ID3FramePartOfTotal(part: 1, total: 3),
		                        .AttachedPicture(.FrontCover) : ID3FrameAttachedPicture(picture: coverArtData!, type: .FrontCover, format: .Jpeg),
		                    ]
		                )
		                
		                let id3TagEditor = ID3TagEditor()
		                try id3TagEditor.write(tag: id3Tag, to: mp3FilePath)
		                
		            } catch {
		                
		                print(error)
		            }
				 }
		 }

4. Click on 'the button'
5. See the resulting mp3 file with any ID3Tag Editor.  Of course you can choose Music.app.  Then you may see discPosition was disappear.  If you comment out .AttachedPicture line, you may see discPosition.

**Screenshots**

**Device (please complete the following information):**
 - Model: MacBook Pro 2018 15inch
 - OS: macOS 10.15.7 Catalina

**Additional context**

[test.zip](https://github.com/chicio/ID3TagEditor/files/5299801/test.zip)

**Comment by chicio** [comment]
Hi @xanadu6291,

thank you for your report. You're right, there was a bug in the frame creator part of ID3TagEditor (specifically in the chain of responsibility). You can find the pull request with the fix here https://github.com/chicio/ID3TagEditor/pull/36 (and also linked above in your issue).
Can you try this version of the library to see if the problem is solved? I added some tests to cover this case. I will merge this PR in the next days but I would like to have your feedback before proceeding.

Thank you,
Fabrizio.

PS.: remember to start ⭐️this repo ⭐️ to support my work!!

**Comment by xanadu6291** [comment]
Hi @chicio,

I  have confirmed that the issue was solved by your fix.  Thank you very much.  Also I have stared your repository... :-)

**Comment by chicio** [comment]
Thank you @xanadu6291 , I will merge the PR now and do a patch release by the end of the day.

**Comment by chicio** [comment]
@xanadu6291 version 3.3.2 released on cocoa pods and SwiftPM. Thank you again.
