### ISSUE TITLE
ID3 v2.4 Does AttachedPicture(.FrontCover) have this error?

### ISSUE THREAD

**Issue by Piorosen** [chicio/ID3TagEditor#37]
**Describe the bug**
In ID3 v2.3, after adding an image, when reading the ID3Tag again, an error does not occur and it operates normally, whereas in v2.4 an error occurs.

**To Reproduce**
```
var test = tagModel.tag.reduce(into: [FrameName:ID3Frame]()) {
    $0[$1.title] = ID3FrameWithStringContent(content: $1.text)
}
if let data = image.jpegData(compressionQuality: 1.0) {
    test[.AttachedPicture(.FrontCover)] = ID3FrameAttachedPicture(picture: data, type: .FrontCover, format: .Jpeg)
}
do {
    try ID3TagEditor().write(tag: ID3Tag(version: .version3, frames: test), to: parentModel.deviceFilePath.path, andSaveTo:
FileManager.default.urls(for: .documentDirectory, in: .allDomainsMask)[0].appendingPathComponent("a.mp3").path)
    try ID3TagEditor().write(tag: ID3Tag(version: .version4, frames: test), to: parentModel.deviceFilePath.path, andSaveTo:
FileManager.default.urls(for: .documentDirectory, in: .allDomainsMask)[0].appendingPathComponent("b.mp3").path)
}catch {
    print(error)
}
```
After saving the a.mp3 file and b.mp3 above,
If you did ID3 Tag Editor().read(from: "a.mp3") there is no problem, but
If ID3 Tag Editor().read(from: "b.mp3") is done, an error occurs.

**Expected behavior**
The exception should be caught at the library level, and nil should be returned if an error occurs.

**Screenshots**
<img width="1350" alt="스크린샷 2020-10-08 오후 12 32 29" src="https://user-images.githubusercontent.com/19870893/95411864-9a978b80-0962-11eb-8088-496dfff7f919.png">
<img width="475" alt="스크린샷 2020-10-08 오후 12 32 47" src="https://user-images.githubusercontent.com/19870893/95411870-9e2b1280-0962-11eb-98f8-0e2220e42627.png">
<img width="934" alt="스크린샷 2020-10-08 오후 12 32 56" src="https://user-images.githubusercontent.com/19870893/95411875-9ff4d600-0962-11eb-915d-2a348f69686f.png">
<img width="934" alt="스크린샷 2020-10-08 오후 12 33 05" src="https://user-images.githubusercontent.com/19870893/95411877-a1260300-0962-11eb-9157-3020105b6877.png">

**Device (please complete the following information):**
 - Model: [Iphone 11 Pro]
 - OS: [iOS 14.0]
 - Emulator

** additional Info **
 - test Image : Here is the below image.
<img width="934" alt="스크린샷 2020-10-08 오후 12 32 56" src="https://user-images.githubusercontent.com/19870893/95411989-e5190800-0962-11eb-80a1-cea5a0b0146d.png">

I am not good English, so I used Google translate. >,&

**Comment by chicio** [comment]
Hi @Piorosen ,

I made some checks on the code and I found an error in the synch safe frame size conversion (this conversion is done/requested only for v4 id3 tags). I opened a new pull request with the fix:

Closes #37: Fix synchsafe v4 frame size #38

Can you try this branch to see if everything works as expected?
In any case I will release a new version on cocoapods and SwiftPM in the next days.

PS remember to support my work by ⭐️ starring ⭐️this repo.

Thank you,
Fabrizio.

**Comment by Piorosen** [comment]
Thank you. And can you some more implement is possible?
ID3TPictureType inherit CaseIterable, but why is FrameName not inherit CaseIterable?
Can't FrameName inherit CaseIterable?

**Comment by chicio** [comment]
Yes it is possible. In fact it makes sense to make all the public enums `CaseIterable` for the case of ID3TagEditor APIs. I will start to merge the bug fix. Develop/Add `CaseIterable` to all the public enum and release a new version of ID3TagEditor (this evening of tomorrow morning). Thank you for your support and I hope  you will find ID3TagEditor useful.

**Comment by chicio** [comment]
Version 3.3.3 release to SwiftPM and cocoapod (and available on the master branch of this repo).

**Comment by Piorosen** [comment]
> Version 3.3.3 release to SwiftPM and cocoapod (and available on the master branch of this repo).

Thank you!!
chicio
