### ISSUE TITLE
Add Comment Frame

### ISSUE THREAD

**Issue by chicio** [chicio/ID3TagEditor#46]
Add support for the `COMM` comment frame.

**Describe the solution you'd like**
Add support for the `COMM` comment frame. This frame has the same structure of `USTL` unsynchronised lyrics. I need to: 

* extract a common `Frame with content description and content` frame class 
   * it would be better a collaborator that contains the common properties
* create `USTL` and `COMM` frame with this new base frame type
* parse and create these frames using the above class

**Additional context**
* See chain of creation and parsing in ID3TagEditor
* https://id3.org/d3v2.3.0 see section "4.11.   Comments"

**Comment by tcarroll2** [comment]
Your documentation and readme do not show this is a supported frame.  Documentation needs updating and an example of how to retrieve this frame and other comment frames would be helpful in the documentation.

**Comment by chicio** [comment]
Hi @tcarroll2 , yes you’re right. I forgot to add it to the documentation when i developed it. I will add it to the documentation. Thanks for the feedback.

**Comment by chicio** [comment]
@tcarroll2 at least in the official doc is there:

https://id3tageditor.fabrizioduroni.it/Enums/FrameName.html#/s:12ID3TagEditor9FrameNameO7commentyAcA0aD15ContentLanguageOcACmF

https://id3tageditor.fabrizioduroni.it/Classes/ID32v4TagBuilder.html#/s:12ID3TagEditor06ID32v4B7BuilderC7comment8language5frameACXDAA0A20FrameContentLanguageO_AA0ai13WithLocalizedJ0CtF
https://id3tageditor.fabrizioduroni.it/Classes/ID32v3TagBuilder.html#/s:12ID3TagEditor06ID32v3B7BuilderC7comment8language5frameACXDAA0A20FrameContentLanguageO_AA0ai13WithLocalizedJ0CtF
https://id3tageditor.fabrizioduroni.it/Classes/ID32v2TagBuilder.html#/s:12ID3TagEditor06ID32v2B7BuilderC7comment8language5frameACXDAA0A20FrameContentLanguageO_AA0ai13WithLocalizedJ0CtF

I will ad just the example in the readme/in the demo apps.

**Comment by chicio** [comment]
documentation and readme updated (version 4.4.2 published)
