### ISSUE TITLE
Restructure project folders

### ISSUE THREAD

**Issue by chicio** [chicio/ID3TagEditor#57]
Change folder structure.

**Describe the solution you'd like**
Remove deep level of folder nesting  in order to have a better navigation in the project.
There should be just one level of folders. If it is not possible we can have an additional second level folder.

**Comment by shreshth6** [comment]
what name you want for first level folder ? if second also, what name you suggest for the same ?

**Comment by chicio** [comment]
Hi @shreshth6 , we can start by keeping the current first level and remove all the nested level. It would be enough to improve the code navigation.

**Comment by chicio** [comment]
FYI: I'm going to merge a big refactoring on master in a few moments. Align your branch/fork before going on with the development.

To make the PR more readable, open 1 pr per folder moved/structured.
