### ISSUE TITLE
Host documentation on GitHub Pages

### ISSUE THREAD

**Issue by franklinyu** [chicio/ID3TagEditor#6]
It would be great if I can browse the documentation online. We can generate it with [Jazzy](https://github.com/realm/jazzy) (manually or by CI).

**Comment by chicio** [comment]
Hi @franklinyu,

it could big a big idea. I started to work on the release 2.0.0  in the last few weeks. After the completion  of these release I could add a mini site wih github pages that contains the doc + the api documentation. In the meantime you can look at the readme and at the examples contained in the project (you can find some "Demo ..." scheme in the xcodeproj).

ps. Remember to support my work by adding this repo to your favourites (start it 😄).

Best regards,
Fabrizio.

**Comment by chicio** [comment]
Hi @franklinyu,
I just released completed the new release 2.0.0 and released it on cocoapods.
In the meantime I also generated the doc. You can find it here:

[https://www.fabrizioduroni.it/ID3TagEditor/](https://www.fabrizioduroni.it/ID3TagEditor/)

Please support my work by starring my repo ⭐️ 

Best regards,
Fabrizio.
