### ISSUE TITLE
USLT Tag not being written to MP3 file

### ISSUE THREAD

**Issue by tcarroll2** [chicio/ID3TagEditor#82]
**Describe the bug**
I have a method that uses ffmpeg as a subprocess to trim silence from the beginning and end of an mp3 track, then it processes it a second time to normalize the audio to LUFS -23.  Before modifying the file, it is preserved (copied) to a new location.

After running the trim process, I am updating the comment via ID3TagEditor to add "trimmed" to the comment field.  I am doing the same thing after the track is normalized, adding "normalized (-23)."

It appears that when I read the id3 tags, then modify the comment tag, then write the id3 back to the file, the lyrics are not being written to the mp3 file.

**To Reproduce**
func writeID3Comment(comment:String, filePath: String) {
        do {
            let id3TagEditor = ID3TagEditor()
            if let id3Tag = try id3TagEditor.read(from: filePath) {
                id3Tag.frames[FrameName.comment(.eng)] = ID3FrameWithLocalizedContent(language: .eng, contentDescription: "", content: comment)
                try id3TagEditor.write(tag: id3Tag, to: filePath)
            }
        } catch {
            print("An error has occurred writing id3Tag comment frame with \(comment) to mp3 file \(filePath)")
        }
    }

**Expected behavior**
I would expect that any tags read with the id3TagEditor.read(from: filePath) would preserve all tags read and write them back out to the file, along with the modified tag(s).

**Screenshots**

**Device (please complete the following information):**
 - Model: iMac (late 2015)
 - OS: macOS Big Sur 11.2.1
 - Xcode 12.4

**Additional context**
Am I not using the id3TagEditor or the id3Tag.frames methods correctly?  Thanks for providing this API!

**Comment by tcarroll2** [comment]
So, I am also including two screen shots of Music Brains Picard that shows the lyrics in the file before changing the comment, and then after.  Unsynchronized lyrics, if present, are not being preserved.  I do not see in the documentation that it is required to capture the USLT frame and write it back to the MP3 file in order to preserve the frame.
<img width="1485" alt="Screen Shot 2021-02-26 at 6 38 32 AM" src="https://user-images.githubusercontent.com/32363030/109301613-d2ae4680-77fd-11eb-8e8a-275ce6586def.png">
<img width="1485" alt="Screen Shot 2021-02-26 at 6 39 48 AM" src="https://user-images.githubusercontent.com/32363030/109301651-dc37ae80-77fd-11eb-87a1-9b1a741759fa.png">

**Comment by tcarroll2** [comment]
In an attempt to find a work-around to this issue, I tried reading the unsynchronized lyrics from the MP3 file and then writing them back after my trimming and normalizing methods, but the unsynchronized lyrics frame is not being read.  Please see the below screen capture. The file referenced with "filePath" property has lyrics in the USLT id3Tag.
<img width="1024" alt="Screen Shot 2021-02-26 at 7 09 15 AM" src="https://user-images.githubusercontent.com/32363030/109304332-b8766780-7801-11eb-9074-05dab3506dce.png">

**Comment by tcarroll2** [comment]
After some more testing, I have found a temporary workaround.  It appears ID3TagEditor is able to write the USLT tag and lyric text to the mp3file.  So, for now, I am grabbing the lyrics from the file via AVAsset().lyrics to preserve the lyrics and then writing the lyrics back to the newly trimmed and normalized mp3 file with ID3TagEditor.

**Comment by chicio** [comment]
Hi @tcarroll2 ,

there could be 2 reason I could think of for your problem:

* the original id3 tag contains a USTL tag that is not implementing the USTL tag in a strict way. ID3TagEditor support only id3 tag that are fully compliant in terms of standard (frame header with all the information, tag structure as reported in the id3 doc etc.)
* USTL tag contains text encoded with a not supported charter set. At the moment ID3TagEditor only support UTF-16. In the future I will add UTF-8 (for id3 tag v4) and ISO latin character sets (these are the ones reported in the official doc).

Anyway I see you found a workaround at the moment. If you need additional help you have to sent me an example mp3 here (copyright free 😁).

Thanks,
Fabrizio.


PS support my work by ⭐️ star ⭐️ this repository ⭐️, thanks ⭐️

**Comment by tcarroll2** [comment]
It's weird because I use Apple Music to manage all my music and I add lyrics to my music within the Music app.  But for some reason ID3TagEditor and Music are not playing nicely. I have since switched to using Apples AVFoundation library and writing the ID3 tags with that.  Thanks for your contribution!
