### ISSUE TITLE
Existing ID3 attributes are cleared when using 'Id3TagEditor.write' 

### ISSUE THREAD

**Issue by kamleshgk** [chicio/ID3TagEditor#83]
**Describe the bug**
I used the macOS demo app and when i try to write properties of an MP3 file using the following code 
All the exiting ID3 attributes in the mp3 file are overwritten.  Is there any way to keep the existing attributes?
`        

         do { 
                     let id3TagAx = ID32v3TagBuilder()
                .title(frame: ID3FrameWithStringContent(content: "Love Come Down (CFLO Intro) Kam1"))
                .artist(frame: ID3FrameWithStringContent(content: "Evelyn Champagne King Kam1"))
                .albumArtist(frame: ID3FrameWithStringContent(content: "Evelyn Champagne King Kam1"))
                .album(frame: ID3FrameWithStringContent(content: "djcflo.com Kam1"))
                .beatsPerMinute(frame: ID3FrameWithIntegerContent(value: 9))
                .mixArtist(frame: ID3FrameWithStringContent(content: "Remix Guy Kam1"))
                .comment(language: ID3FrameContentLanguage(rawValue: "eng")!,
                         frame: ID3FrameWithLocalizedContent(language: ID3FrameContentLanguage.eng,
                                                             contentDescription: "Comment",
                                                             content: "Kam is here Kam1"))
                .build()
             try id3TagEditor.write(
                tag: id3TagAx,
                to: "/Users/kamyfc/Music/KamySongs/CFLO 12.19/Stevie Wonder - Signed Sealed Delivered (CFLO Edit).mp3"
            )
        } catch {
            print(error)
        }
`

**To Reproduce**
1. Ensure you see many attributes in MP3 files.
2. Write an update values of few attributes to an MP3 file using ID3TagEditor demo app
2. Observe the attributes
4. See that existing attributes are wiped away.

**Expected behavior**
Ideally existing attributes should not be cleared away. We need to update the values of the attributes that are edited and retain other attributes.

**Screenshots**
The data on right shows the ID3 data before editing using ID3TagEditor. The data on left shows after using the 'Id3TagEditor.write' method. As you can see how existing attributes on the right are cleared away.
https://pasteboard.co/JRda9gg.png

**Device (please complete the following information):**
 - Model: Mac Mini 2018
 - OS: macOS Catalina

**Additional context**

**Comment by chicio** [comment]
Hi @kamleshgk ,

this is a design choice I made during the creation of ID3TagEditor. When you use the `write` methods they replace the current tag with a new one. If you would like to maintain the current tag and add some data to it, you have to:

* read the current tag 
* add to it the new data
* write it with the write method

I suggest t use the methods that works with `Data` data type and save the file in your code.

PS support my work by ⭐️ star ⭐️ this repository ⭐️, thanks ⭐️
