### ISSUE TITLE
exceeds data length error on some mp3 files with version4

### ISSUE THREAD

**Issue by andriypohorilko** [chicio/ID3TagEditor#88]
I get an error -[Foundation.__NSSwiftData subdataWithRange:]: range {115888, 24847503} exceeds data length 11634651
on trying to read mp3 songs with version4.

I've uploaded the mp3 file below.

I use ID3TagEditor 4.1.3

**Steps to reproduce the behavior:**
1. Go to Example App macOS version
2. Add file "The Black Eyed Peas - I Gotta Feeling" to the project
3. Change "pathFor(name:)" in ViewController file, line 20 to "The Black Eyed Peas - I Gotta Feeling"
4. Run the app

[The Black Eyed Peas - I Gotta Feeling.mp3.zip](https://github.com/chicio/ID3TagEditor/files/8009006/The.Black.Eyed.Peas.-.I.Gotta.Feeling.mp3.zip)

**Comment by andriypohorilko** [comment]
Problem is in ID3FramesParser.parse(mp3:id3Tag:) func.
At some point NSRange(location: currentFramePosition, length: frameSize) becomes bigger than mp3.length itself.

So, this code seems to solve the issue but I don't think this is the correct way.
`            if currentFramePosition + frameSize > mp3.length {
                return
            }`
            
<img width="844" alt="Screenshot 2022-02-06 at 10 36 54" src="https://user-images.githubusercontent.com/18321399/152673613-e553ec2f-d32e-4b69-8bca-dc1ac2a2c6d2.png">

**Comment by chicio** [comment]
Hi @andriypohorilko ,

this error could happen if:

- the id3 tag is not well formed with respect to the standard (ID3TagEditor is strict)
- the id3 tag contains some encoding for the text frames that it is still not supported

I will try to debug it in the following weekends. If you discover something new just let me know. 
Thank you for using ID3TagEditor.

Fabrizio.

**Comment by chicio** [comment]
Hi @andriypohorilko, I debug your mp3 and put in place some test. The problem is related to how it is stored the attached picture frame size. Seems like your mp3 has this data saved as a normal integer instead of a Synchsafe one. Anyway I will try to add a fallback to support your case (because seems like other reader are not following the standard strictly as I do). I will keep you updated.

**Comment by chicio** [comment]
Hi @andriypohorilko, I made further investigation and I was wrong. The size reported in a frame after the APIC (images) is wrong. I would close these as the only thing I could do is doing a fallback like the one you suggested and keep the frames parsed until that moment.
