### ISSUE TITLE
ID3FrameRecordingYear is out of scope

### ISSUE THREAD

**Issue by xanadu6291** [chicio/ID3TagEditor#89]
**Describe the bug**
It may not be a bug, but mistake of readme.md.  .recordingYear(frame: ID3FrameRecordingYear(year: 2020)) is wrong.

**To Reproduce**
.recordingYear(frame: ID3FrameRecordingYear(year: 2020)) can't compile in Swift.
It should be written as .recordingYear(frame: ID3FrameWithIntegerContent(value: 2020))

**Expected behavior**
Compile should be finished without problem.

**Screenshots**
None

**Device (please complete the following information):**
 - Model: MacBook Pro 2018
 - OS: macOS12.3.1

**Additional context**
None

**Comment by chicio** [comment]
Hi @xanadu6291 ,

thank you for your reporting. You're right, the doc in the readme is not aligned with the code. I fixed it. You can find it on master (and eventually in the next release with other updates).

Fabrizio.

PS remember to ⭐  star ⭐  this repo in order to support my open source work 🚀
