### ISSUE TITLE
Can't Read Cover

### ISSUE THREAD

**Issue by rastaman111** [chicio/ID3TagEditor#97]
Hello!
If I use an example file, then it reads her cover, but when I upload mine, it gives nil

What's the problem, everything else reads
<img width="232" alt="Снимок экрана 2022-12-02 в 14 40 51" src="https://user-images.githubusercontent.com/15727518/205285058-7d18be2e-bd9f-48ca-9972-229d287f7516.png">

<img width="1744" alt="Снимок экрана 2022-12-02 в 14 41 06" src="https://user-images.githubusercontent.com/15727518/205285093-9840e79c-832b-48d4-ac23-834e02b41b6c.png">

**Comment by lordzsolt** [comment]
@rastaman111 You will need to provide the example file, or debug it yourself.

Without seeing what's in the file, there's no way to know why the cover can't be read.

**Comment by rastaman111** [comment]
[Neidonhard - Baloney.mp3.zip](https://github.com/chicio/ID3TagEditor/files/10304585/Neidonhard.-.Baloney.mp3.zip)
Hello! I attach a file

**Comment by chicio** [comment]
@rastaman111 thanks for uploading the example (and sorry for the late reply). I will try to give a look at this in the future (at the moment I'm busy on another project).
Usually this happens if the image has some problem in the metadata/magic number to recognize it. 
Can you share also the piece of code that you wrote in order to add the image to the tag?

thanks,
Fabrizio.

**Comment by rastaman111** [comment]
I took the code from your library example and put my file, after which I clicked to read tags, it seems to read everything except pictures.  I have an application where a picture is read by the file metadata

![image](https://user-images.githubusercontent.com/15727518/209662045-ca3f2665-40b1-46ca-8e32-8f8f4859bf80.png)

**Comment by lordzsolt** [comment]
@rastaman111 The cover is read correctly, according to the ID3 specification.

The type of the image is `.other`, so you need to access it as:
`id3Tag.frames[.attachedPicture(.other)]`

Though I would recommend using `ID3TagContentReader` and just do:

```swift
let contentReader = ID3TagContentReader(id3Tag: id3Tag)
let cover = contentReader.attachedPictures().first
```
